# Default values for pikaflask.

replicaCount: 1

image:
  repository: oskarq/pikaflask
  pullPolicy: IfNotPresent
  tag: v2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

# works curl ingress-lba-IP without /pikablu but with clusterIP service
ingress:
  enabled: true
  className: nginx
  annotations: 
    # nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "" 
      paths:
        - path: /
          pathType: Prefix
          # backend:
          #   serviceName: pikablu  
          #   servicePort: 80 

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: 5000
readinessProbe:
  httpGet:
    path: /health
    port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
